project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Traffic Safety"
  author:
    - Akshayaa Shrestha (as7460)
    - Rujula Pradeep (rp3248)
  repo-url: https://github.com/akshu981/Traffic-Safety
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


